### ISSUE TITLE
Read image path from the Webpack manifest file

### ISSUE THREAD

**Issue by wildvalcom** [sheerun/babel-plugin-file-loader#10]
Hi,

In the company where I work, we have a scenario where we need to read the paths from the wepback manifest files. I created this functionality on top of this plugin.
Are you interested in PR with this functionality?

**Comment by sheerun** [comment]
Honestly I'm not sure what you mean by "read the paths from the wepback manifest files" and what is the use case

**Comment by frenzzy** [comment]
Probably it is about creating a list of all assets to be able to use it inside [ServiceWorker](https://developers.google.com/web/tools/workbox/modules/workbox-precaching).
There are should be a way to update assets in client-side cache after deploy - remove outdated files and preload new.

**Comment by nsunga** [comment]
@wildvalcom Was it for server side rendering or developing isomorphic apps? I wouldve been interested :(
